before_script:
  - mkdir build
  - cd build
  - ./configure --disable-interactive --enablegnutls --enable-epoll --prefix=test

script:
  - make

notifications:
  irc:
  - "irc.furryavalon.net#FurryAvalon"
