dist: trusty
env:
  - TEST_BUILD_DYNAMIC=1
  - TEST_BUILD_STATIC=1
language: cpp
matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env: COMPILER=g++-4.9
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env: COMPILER=g++-5
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - clang-3.6
      env: COMPILER=clang++-3.6
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
      env: COMPILER=clang++-3.7
notifications:
  email: false
script:
  - sh ./tools/travis-ci.sh
sudo: required

# Remember, Travis needs to be able to connect to the server so if the IRC server's dead, UPDATE the server address!
notifications:
  irc:
  - "irc.heimkoma.com#irc"

# blacklist
branches:
    - insp10
    - insp11
    - insp12
    - obsolete/insp21

# whitelist
branches:
  only:
    - master
    - insp20
